### ISSUE TITLE
Add website to description

### ISSUE THREAD

**Issue by procgen** [CodingTrain/Oregon-Trail#35]
In order to test/play it without downloading it add this URL as website:
https://codingtrain.github.io/Oregon-Trail/

**Comment by Rodak123** [comment]
Made a pull request #34, but named it wrong,  sorry.

**Comment by procgen** [comment]
True you can also put it into the README.md.
I thought about this section:
![image](https://user-images.githubusercontent.com/94574013/203433260-f86e1b3b-3ee3-4958-bc3e-31b60e985b9c.png)

**Comment by shiffman** [comment]
Thank you @procgen I'll add it! I'd like to add more documentation to the README and include links to the livestreams, etc. Happy for someone to work on this!

**Comment by shiffman** [comment]
About section is complete!
