### ISSUE TITLE
Slides or Pages?

### ISSUE THREAD

**Issue by Rodak123** [CodingTrain/Oregon-Trail#38]
It seems like there should be only one in use.

So that code like this:
```js
// From js/slide_manager.js lines 107-112
changePageTo(name) {
    const page = this.getSlideByName(name);
    if (page != undefined) {
        this.currentSlide = page;
    }
}
```
is less confusing:
```js
changeSlideTo(name) {
    const slide = this.getSlideByName(name);
    if (slide != undefined) {
        this.currentSlide = slide;
    }
}
```
I can refactor it, but I need to know which one.

**Comment by shiffman** [comment]
I kind of like the idea of "page" over "slide"? It's more clear to me and in line with the game being 40+ years old. Maybe we should rename everything? Don't feel super strongly about this though!
